### ISSUE TITLE
Recipe requirements out of sync with requirements.txt

### ISSUE THREAD

**Issue by scottyhq** [conda-forge/argopy-feedstock#15]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

@ocefpaf @gmaze some packages like `gsw` can apparently be removed.

Comparing
https://github.com/euroargodev/argopy/blob/v0.1.13/requirements.txt

With https://github.com/conda-forge/argopy-feedstock/blob/6f4a1368fa0fea88976b2c150f384e16c33a234c/recipe/meta.yaml#L18-L38

### Installed packages

```shell
n/a
```

### Environment info

Ran into this issue trying to get as up-to-date versions of gsw, erddapy, and argopy in the same environment (https://github.com/pangeo-data/pangeo-docker-images/pull/461#discussion_r1326746636)

**Comment by ocefpaf** [comment]
I'll leave to @gmaze to define if we should remove the extras or not. But my guess is that we can drop the gsw pin there and things should work.

**Comment by gmaze** [comment]
Yes, we can drop gsw and basically the extra (dask-core, gsw, scikit-learn)

what must be there is:

- xarray>=0.18
- scipy>=1.5
- netCDF4>=1.5.3 #<1.5.9
- toolz>=0.8.2
- erddapy>=0.7
- fsspec>=0.8
- aiohttp>=3.7
- packaging>=20.4
- requests>=2.28
