### ISSUE TITLE
v0.1.9 conda build not triggered ?

### ISSUE THREAD

**Issue by gmaze** [conda-forge/argopy-feedstock#9]
Hi @ocefpaf , could you please have a look about the conda feedstock not being updated automatically to pypi version 0.1.9 of argopy ?
(I still don't get how this is working)
Thanks a lot !!

**Comment by ocefpaf** [comment]
It did in #10, sometimes the bot is a bit overwhelmed and it can take a few extra hours for the PR to show up.
